---

  - name: Ensure destition dir exists
    file: path=/app state=directory owner=devopsapp mode=0755

  - name: Copy application
    copy: src=/repo/nodejsapp dest=/apps owner=devopsapp mode=0744

  - include: install.yml

  - name: Start application
    command: "npm start"
    args:
      chdir: /apps/nodejsapp
